Vit_Models:
  vit-base-patch16-224-in21k: "google/vit-base-patch16-224-in21k"
  vit-base-patch32-224-in21k: "google/vit-base-patch32-224-in21k"
  vit-large-patch16-224-in21k: "google/vit-large-patch16-224-in21k"
  dino-vitb8: "facebook/dino-vitb8"
  dino-vits8: "facebook/dino-vits8"
  vit-dino16: "facebook/dino-vits16"
  deit-base-distilled-patch16-224: "facebook/deit-base-distilled-patch16-224"
  owkin/phikon: "owkin/phikon"
  
  
