Timm_Models:
  res2net50_14w_8s_in1k: 'res2net50_14w_8s.in1k'
  res2net50_26w_4s_in1k: 'res2net50_26w_4s.in1k'
  res2net50_26w_6s_in1k: 'res2net50_26w_6s.in1k'
  res2net50_26w_8s_in1k: 'res2net50_26w_8s.in1k'
  xception41_tf_in1k: 'xception41.tf_in1k'
  xception41p_ra3_in1k: 'xception41p.ra3_in1k'
  xception65_ra3_in1k: 'xception65.ra3_in1k'
  xception65_tf_in1k: 'xception65.tf_in1k'
  xception65p_ra3_in1k: 'xception65p.ra3_in1k'
  xception71_tf_in1k: 'xception71.tf_in1k'
  inception_v3_gluon_in1k: 'inception_v3.gluon_in1k'
  inception_v3_tf_adv_in1k: 'inception_v3.tf_adv_in1k'
  inception_v3_tf_in1k: 'inception_v3.tf_in1k'
  inception_v3_tv_in1k: 'inception_v3.tv_in1k'
  inception_v4_tf_in1k: 'inception_v4.tf_in1k'